cora:
  lr: 0.001
  lr_f: 0.01
  num_hidden: 512
  num_heads: 4
  num_layers: 2
  weight_decay: 2e-4
  weight_decay_f: 1e-4
  max_epoch: 1500
  max_epoch_f: 300
  mask_rate: 0.5 #0.1 0.5 0.002
  num_layers: 2
  encoder: gat
  decoder: gat
  activation: prelu
  in_drop: 0.2
  attn_drop: 0.1
  linear_prob: True
  loss_fn: sce
  drop_edge_rate: 0.0
  optimizer: adam
  replace_rate: 0.05
  alpha_l: 3
  scheduler: True


wiki:
  lr: 0.001
  lr_f: 0.01
  num_hidden: 512
  num_heads: 4
  num_layers: 2
  weight_decay: 2e-4
  weight_decay_f: 1e-4
  max_epoch: 1500
  max_epoch_f: 300
  mask_rate: 0.5 #0.1 0.5 0.002
  num_layers: 2
  encoder: gat
  decoder: gat
  activation: prelu
  in_drop: 0.2
  attn_drop: 0.1
  linear_prob: True
  loss_fn: sce
  drop_edge_rate: 0.0
  optimizer: adam
  replace_rate: 0.05
  alpha_l: 3
  scheduler: True
texas:
  lr: 0.0005
  lr_f: 0.01
  num_hidden: 256
  num_heads: 4
  weight_decay: 2e-4
  weight_decay_f: 1e-4
  max_epoch: 500
  max_epoch_f: 300
  mask_rate: 0.5 #0.1 0.5 0.002
  num_layers: 1
  encoder: gat
  decoder: gat
  activation: prelu
  in_drop: 0.2
  attn_drop: 0.1
  linear_prob: True
  loss_fn: sce
  drop_edge_rate: 0.0
  optimizer: adam
  replace_rate: 0.05
  alpha_l: 1
  scheduler: True


 
cornell:
  lr: 0.0005
  lr_f: 0.01
  num_hidden: 1024
  num_heads: 8
  weight_decay: 2e-4
  weight_decay_f: 1e-4
  max_epoch: 500
  max_epoch_f: 300
  mask_rate: 0.3 #0.1 0.5 0.002
  num_layers: 1
  encoder: gat
  decoder: gat
  activation: relu
  in_drop: 0.2
  attn_drop: 0.1
  linear_prob: True
  loss_fn: sce
  drop_edge_rate: 0.0
  optimizer: adam
  replace_rate: 0.0 #seed 42 0.05
  alpha_l: 2
  scheduler: True
  residual: True


chame:
  lr: 0.0001
  lr_f: 0.01
  num_hidden: 1024
  num_heads: 2
  num_layers: 2
  weight_decay: 1e-4 #5e-6
  weight_decay_f: 1e-4
  max_epoch: 1500
  max_epoch_f: 300
  mask_rate: 0.5 #0.1 0.5 0.002
  encoder: gat
  decoder: gat
  activation: prelu
  in_drop: 0.2
  attn_drop: 0.1
  linear_prob: True
  loss_fn: sce
  drop_edge_rate: 0.0
  optimizer: adam
  replace_rate: 0.1
  alpha_l: 3
  scheduler: True
  residual: True


chame_f:
  lr: 0.001
  lr_f: 0.01
  num_hidden: 1024
  num_heads: 8
  num_layers: 2
  weight_decay: 2e-4
  weight_decay_f: 1e-4
  max_epoch: 2000
  max_epoch_f: 300
  mask_rate: 0.5 #0.1 0.5 0.002
  num_layers: 2
  encoder: gat
  decoder: gat
  activation: prelu
  in_drop: 0.2
  attn_drop: 0.1
  linear_prob: True
  loss_fn: sce
  drop_edge_rate: 0.0
  optimizer: adam
  replace_rate: 0.1
  alpha_l: 3
  scheduler: True
croco:
  lr: 0.001
  lr_f: 0.01
  num_hidden: 2048
  num_heads: 4
  num_layers: 2
  weight_decay: 2e-5
  weight_decay_f: 1e-4
  max_epoch: 3000
  max_epoch_f: 300
  mask_rate: 0.5 #0.1 0.5 0.002
  encoder: gat
  decoder: gat
  activation: prelu
  in_drop: 0.2
  attn_drop: 0.1
  linear_prob: True
  loss_fn: sce
  drop_edge_rate: 0.0
  optimizer: adam
  replace_rate: 0.00
  alpha_l: 3
  scheduler: True
act:
  lr: 0.01 #0.0005
  lr_f: 0.01
  num_hidden: 128
  num_heads: 4
  num_layers: 1
  weight_decay: 2e-4 #2e-4
  weight_decay_f: 1e-4
  max_epoch: 1000
  max_epoch_f: 300
  mask_rate: 0.5 #0.1 0.5 0.002
  encoder: gat
  decoder: gat
  activation: prelu
  in_drop: 0.2
  attn_drop: 0.1
  linear_prob: True
  loss_fn: sce
  drop_edge_rate: 0.0
  optimizer: adam
  replace_rate: 0.05
  alpha_l: 2
  scheduler: True

squ:
  lr: 0.005
  lr_f: 0.01
  num_hidden: 2048
  num_heads: 2
  num_layers: 1
  weight_decay: 1e-5
  weight_decay_f: 1e-4
  max_epoch: 2000
  max_epoch_f: 300
  mask_rate: 0.5 #0.1 0.5 0.002
  encoder: gat
  decoder: gat
  activation: prelu
  in_drop: 0.2
  attn_drop: 0.1
  linear_prob: True
  loss_fn: sce
  drop_edge_rate: 0.0
  optimizer: adam
  replace_rate: 0.1
  alpha_l: 3
  scheduler: True




squ_f:
  lr: 0.001
  lr_f: 0.01
  num_hidden: 1024
  num_heads: 8
  num_layers: 2
  weight_decay: 2e-5
  weight_decay_f: 1e-4
  max_epoch: 2000
  max_epoch_f: 300
  mask_rate: 0.5 #0.1 0.5 0.002
  num_layers: 2
  encoder: gat
  decoder: gat
  activation: prelu
  in_drop: 0.2
  attn_drop: 0.1
  linear_prob: True
  loss_fn: sce
  drop_edge_rate: 0.0
  optimizer: adam
  replace_rate: 0.00
  alpha_l: 3
  scheduler: True

Wis:
  lr: 0.0005
  lr_f: 0.01
  num_hidden: 256
  num_heads: 8
  weight_decay: 2e-4
  weight_decay_f: 1e-4
  max_epoch: 500
  max_epoch_f: 300
  mask_rate: 0.3 #0.1 0.5 0.002
  num_layers: 1
  encoder: gat
  decoder: gat
  activation: prelu
  in_drop: 0.2
  attn_drop: 0.1
  linear_prob: True
  loss_fn: sce
  drop_edge_rate: 0.0
  optimizer: adam
  replace_rate: 0.0
  alpha_l: 2
  scheduler: True
  #residual: True

roman:
  lr: 0.001
  lr_f: 0.01
  num_hidden: 1024
  num_heads: 8
  num_layers: 1
  weight_decay: 2e-4
  weight_decay_f: 1e-4
  max_epoch: 500
  max_epoch_f: 300
  mask_rate: 0.8 #0.1 0.5 0.002
  num_layers: 2
  encoder: gat
  decoder: gat
  activation: prelu
  in_drop: 0.2
  attn_drop: 0.1
  linear_prob: True
  loss_fn: sce
  drop_edge_rate: 0.0
  optimizer: adam
  replace_rate: 0.05
  alpha_l: 3
  concat_hidden: True
  scheduler: True
  norm: layernorm

syn:
  lr: 0.001
  lr_f: 0.01
  num_hidden: 1024
  num_heads: 4
  num_layers: 2
  weight_decay: 2e-4
  weight_decay_f: 1e-4
  max_epoch: 1500
  max_epoch_f: 300
  mask_rate: 0.5 #0.1 0.5 0.002
  num_layers: 2
  encoder: gat
  decoder: gat
  activation: prelu
  in_drop: 0.2
  attn_drop: 0.1
  linear_prob: True
  loss_fn: sce
  drop_edge_rate: 0.0
  optimizer: adam
  replace_rate: 0.05
  alpha_l: 1
  scheduler: True
dee:
  lr: 0.001
  lr_f: 0.01
  num_hidden: 512
  num_heads: 8
  num_layers: 2
  weight_decay: 2e-5
  weight_decay_f: 1e-4
  max_epoch: 3000
  max_epoch_f: 300
  mask_rate: 0.75 #0.1 0.5 0.002
  num_layers: 2
  encoder: gat
  decoder: gat
  activation: prelu
  in_drop: 0.2
  attn_drop: 0.1
  linear_prob: True
  loss_fn: sce
  drop_edge_rate: 0.0
  optimizer: adam
  replace_rate: 0.05
  alpha_l: 3
  scheduler: True
  norm: layernorm
  concat_hidden: True
  residual: True
  
amr:
  lr: 0.001
  lr_f: 0.01
  num_hidden: 1024
  num_heads: 4
  num_layers: 2
  weight_decay: 2e-4
  weight_decay_f: 1e-4
  max_epoch: 2000
  max_epoch_f: 300
  mask_rate: 0.75 #0.1 0.5 0.002
  num_layers: 2
  encoder: gat
  decoder: gat
  activation: prelu
  in_drop: 0.2
  attn_drop: 0.1
  linear_prob: True
  loss_fn: sce
  drop_edge_rate: 0.0
  optimizer: adam
  replace_rate: 0.05
  alpha_l: 3
  scheduler: True
  norm: layernorm
  #residual: True
  concat_hidden: True

mines:
  lr: 0.001
  lr_f: 0.01
  num_hidden: 512
  num_heads: 4
  num_layers: 2
  weight_decay: 2e-4
  weight_decay_f: 1e-4
  max_epoch: 2000
  max_epoch_f: 300
  mask_rate: 0.5 #0.1 0.5 0.002
  num_layers: 2
  encoder: gat
  decoder: gat
  activation: prelu
  in_drop: 0.2
  attn_drop: 0.1
  linear_prob: True
  loss_fn: sce
  drop_edge_rate: 0.0
  optimizer: adam
  replace_rate: 0.00
  alpha_l: 3
  scheduler: True
citeseer:
  lr: 0.001
  lr_f: 0.01
  num_hidden: 512
  num_heads: 2
  num_layers: 2
  weight_decay: 2e-5
  weight_decay_f: 0.01
  max_epoch: 300
  max_epoch_f: 300
  mask_rate: 0.5 #{0.2 0.005 0.6}
  num_layers: 2
  encoder: gat
  decoder: gat
  activation: prelu
  in_drop: 0.2  
  attn_drop: 0.1
  linear_prob: True
  loss_fn: sce
  drop_edge_rate: 0.0
  optimizer: adam
  replace_rate: 0.1
  alpha_l: 1 # or 3 
  scheduler: True
pubmed:
  lr: 0.0008
  lr_f: 0.01
  num_hidden: 1024
  num_heads: 4
  num_layers: 2
  weight_decay: 1e-5
  weight_decay_f: 1e-4
  max_epoch: 1000
  max_epoch_f: 300
  mask_rate: 0.75
  num_layers: 2
  encoder: gat
  decoder: gat
  activation: prelu
  in_drop: 0.2
  attn_drop: 0.1
  linear_prob: True
  loss_fn: sce
  drop_edge_rate: 0.0
  optimizer: adam
  replace_rate: 0.0
  alpha_l: 3
  scheduler: True
  save_model: True
ogbn-arxiv:
  lr: 0.001
  lr_f: 0.01
  num_hidden: 1024
  num_heads: 4
  weight_decay: 1e-4
  weight_decay_f: 5e-4
  max_epoch: 2000
  max_epoch_f: 600
  mask_rate: 0.5
  drop_edge_rate: 0.5
  num_layers: 3
  encoder: gat
  decoder: gat 
  activation: prelu
  in_drop: 0.2
  attn_drop: 0.1
  linear_prob: True
  loss_fn: sce
  replace_rate: 0.0
  alpha_l: 3 # 2
  scheduler: True
  norm: layernorm
arxiv-years:
  lr: 0.001
  lr_f: 0.01
  num_hidden: 128
  num_heads: 4
  weight_decay: 1e-4
  weight_decay_f: 5e-4
  max_epoch: 500
  max_epoch_f: 600
  mask_rate: 0.75
  drop_edge_rate: 0.2
  num_layers: 3
  encoder: gat
  decoder: gat 
  activation: prelu
  in_drop: 0.2
  attn_drop: 0.1
  linear_prob: True
  loss_fn: sce
  replace_rate: 0.0
  alpha_l: 3 # 2
  scheduler: True
  norm: layernorm
  concat_hidden: True
    #residual: True
penn94:
  lr: 0.001
  lr_f: 0.01
  num_hidden: 512
  num_heads: 4
  weight_decay: 1e-4
  weight_decay_f: 1e-4
  max_epoch: 1500
  max_epoch_f: 600
  mask_rate: 0.5
  drop_edge_rate: 0.0
  num_layers: 2
  encoder: gat
  decoder: gat 
  activation: prelu
  in_drop: 0.2
  attn_drop: 0.1
  linear_prob: True
  loss_fn: sce
  replace_rate: 0.0
  alpha_l: 3 # 2
  scheduler: True
  #norm: layernorm
  #concat_hidden: True

ppi:
  lr: 0.0001 # 1e-4 for hidden=1024/2048, 2e-5 for hidden=8192, 5e-6 for hidden=16384
  lr_f: 0.005
  num_hidden: 1024
  num_heads: 4
  weight_decay: 0
  weight_decay_f: 0
  max_epoch: 1000
  max_epoch_f: 2000
  mask_rate: 0.5
  num_layers: 3
  encoder: gat
  decoder: gat
  activation: prelu
  in_drop: 0.2
  loss_fn: sce
  optimizer: adam
  replace_rate: 0.1 # 0.1 for 256*4, else 0. 
  drop_edge_rate: 0.0
  alpha_l: 3
  norm: layernorm
  residual: True
  scheduler: True
  linear_prob: True
reddit:
  lr: 0.001
  lr_f: 0.005
  num_hidden: 512
  num_heads: 2
  weight_decay: 2e-4
  weight_decay_f: 0
  max_epoch: 500
  max_epoch_f: 500
  mask_rate: 0.75
  num_layers: 4
  encoder: gat
  decoder: gat
  activation: prelu
  in_drop: 0.2
  loss_fn: sce
  optimizer: adam
  replace_rate: 0.15
  drop_edge_rate: 0.5
  alpha_l: 3
  norm: layernorm
  residual: True
  scheduler: True
  linear_prob: True

phy:
  lr: 0.001
  lr_f: 0.01
  num_hidden: 512
  num_heads: 4
  num_layers: 2
  weight_decay: 2e-4
  weight_decay_f: 1e-4
  max_epoch: 1500
  max_epoch_f: 300
  mask_rate: 0.5 #0.1 0.5 0.002
  num_layers: 2
  encoder: gat
  decoder: gat
  activation: prelu
  in_drop: 0.2
  attn_drop: 0.1
  linear_prob: True
  loss_fn: sce
  drop_edge_rate: 0.0
  optimizer: adam
  replace_rate: 0.05
  alpha_l: 3
  scheduler: True
  sava_model: True
  #load_model: True

cs:
  lr: 0.001
  lr_f: 0.01
  num_hidden: 512
  num_heads: 4
  num_layers: 2
  weight_decay: 1e-4
  weight_decay_f: 1e-4
  max_epoch: 1500
  max_epoch_f: 300
  mask_rate: 0.5 #0.1 0.5 0.002
  num_layers: 2
  encoder: gat
  decoder: gat
  activation: prelu
  in_drop: 0.2
  attn_drop: 0.1
  linear_prob: True
  loss_fn: sce
  drop_edge_rate: 0.0
  optimizer: adam
  replace_rate: 0.05
  alpha_l: 3
  scheduler: True
  sava_model: True
  #load_model: True
  residual: True

computer:
  lr: 0.001
  lr_f: 0.01
  num_hidden: 512
  num_heads: 4
  num_layers: 2
  weight_decay: 2e-4
  weight_decay_f: 1e-4
  max_epoch: 1000 #1000就好
  max_epoch_f: 300
  mask_rate: 0.5 #0.1 0.5 0.002
  num_layers: 2
  encoder: gat
  decoder: gat
  activation: prelu
  in_drop: 0.2
  attn_drop: 0.1
  linear_prob: True
  loss_fn: sce
  drop_edge_rate: 0.0
  optimizer: adam
  replace_rate: 0.05
  alpha_l: 3
  scheduler: True
  #sava_model: True
  load_model: True
photo:
  lr: 0.001
  lr_f: 0.01
  num_hidden: 512
  num_heads: 4
  num_layers: 2
  weight_decay: 2e-4
  weight_decay_f: 1e-4
  max_epoch: 1500
  max_epoch_f: 300
  mask_rate: 0.5 #0.1 0.5 0.002
  num_layers: 2
  encoder: gat
  decoder: gat
  activation: prelu
  in_drop: 0.2
  attn_drop: 0.1
  linear_prob: True
  loss_fn: sce
  drop_edge_rate: 0.0
  optimizer: adam
  replace_rate: 0.05
  alpha_l: 3
  scheduler: True
  #save_model: True
  #load_model: True
twitch_gamer:
  lr: 0.001
  lr_f: 0.01
  num_hidden: 512
  num_heads: 2
  weight_decay: 2e-4
  weight_decay_f: 5e-4
  max_epoch: 2000
  max_epoch_f: 600
  mask_rate: 0.75
  drop_edge_rate: 0.0
  num_layers: 2
  encoder: gat
  decoder: gat
  activation: prelu
  in_drop: 0.2
  attn_drop: 0.1
  linear_prob: True
  loss_fn: sce
  replace_rate: 0.1
  alpha_l: 3 # 2
  scheduler: True
  norm: layernorm
  #concat_hidden: True
  #residual: True
  #load_model: True